/*
  The motion tokens, generated.

    ELECTRON_RUN_AS_NODE=1 node_modules/electron/dist/electron.exe scripts/motion-tokens.cjs

  writes src/renderer/motion/tokens.css (CSS custom properties) and
  src/renderer/motion/tokens.generated.ts (the same numbers for code), and
  tests/MotionTokens.test.ts fails if either is out of date with this file.

  Springs are described the way Apple describes them (WWDC23 "Animate with
  springs"): a perceptual DURATION and a BOUNCE, not stiffness and damping.

      stiffness = (2 pi / duration)^2      damping = 4 pi (1 - bounce) / duration

  with a mass of 1. Bounce 0 is critically damped: it arrives as fast as it
  can without overshooting. The curve is sampled into CSS `linear()` so it runs
  as an ordinary transition, on the compositor, with no library and no
  JavaScript per frame. A spring takes longer to settle than its perceptual
  duration (it creeps in over the last few percent), so each one also gets the
  time it really needs: that is the CSS duration to use with it.
*/

'use strict';

const { writeFileSync } = require('node:fs');
const { join } = require('node:path');

/**
 * THE bounce of everything that moves in space: dialogs, panels, menus,
 * toasts, switches, segmented controls, the start screen's cards, the export
 * check mark. 0.25 is playful - a visible 3% overshoot on a dialog. Turn it
 * down here (0.15 is a hint, 0 is none) and run this script.
 */
const BOUNCE = 0.25;

/** Perceptual durations, in seconds, by how big the thing that moves is. */
const SPRINGS = {
  /** Switches, segmented controls, tab indicators, a press. */
  quick: 0.15,
  /** Menus, popovers, toasts, tooltips. */
  standard: 0.25,
  /** Dialogs and panels. */
  emphasis: 0.35,
};

/** Everything that is not a spring. Milliseconds unless said otherwise. */
const FIXED = {
  /** Hover and colour changes: they never bounce. */
  'dur-micro': '120ms',
  /** Leaving: short, accelerating, never bouncing. Nobody waits for an exit. */
  'dur-exit': '120ms',
  /** Leaving for things that open by the dozen: menus, tooltips. */
  'dur-exit-fast': '90ms',
  /** Reduced motion: everything is a fade this long, nothing moves. */
  'dur-reduced': '100ms',
  'ease-exit': 'cubic-bezier(0.4, 0, 1, 1)',
  'ease-standard': 'cubic-bezier(0.2, 0, 0, 1)',
  'ease-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
  /** How far things travel. Small: motion says where, it does not tour. */
  'shift-xs': '4px',
  'shift-sm': '8px',
  'shift-md': '16px',
  /** What a dialog, menu or popover grows from. */
  'scale-enter': '0.96',
};

const EPSILON = 0.002;
const STEPS = 40;

/** Position (0 -> 1) of a spring released at rest, at time t seconds. */
function springAt(duration, bounce, t) {
  const stiffness = (2 * Math.PI / duration) ** 2;
  const damping = (4 * Math.PI * (1 - bounce)) / duration;
  const w0 = Math.sqrt(stiffness);
  const zeta = damping / (2 * w0);
  if (zeta < 1) {
    const wd = w0 * Math.sqrt(1 - zeta * zeta);
    return 1 - Math.exp(-zeta * w0 * t) * (Math.cos(wd * t) + ((zeta * w0) / wd) * Math.sin(wd * t));
  }
  return 1 - Math.exp(-w0 * t) * (1 + w0 * t);
}

/** Sample a spring into `linear()` points, over the time it takes to settle. */
function spring(duration, bounce) {
  let settle = 0;
  for (let t = 0; t < 5; t += 0.001) if (Math.abs(1 - springAt(duration, bounce, t)) > EPSILON) settle = t;
  settle = Math.ceil(settle * 100) / 100;
  const points = [];
  let peak = 0;
  for (let i = 0; i <= STEPS; i += 1) {
    const value = springAt(duration, bounce, (i / STEPS) * settle);
    peak = Math.max(peak, value);
    points.push(Number(value.toFixed(3)));
  }
  // It ends exactly at rest, or the last frame jumps.
  points[STEPS] = 1;
  return {
    settleMs: Math.round(settle * 1000),
    overshoot: Number(Math.max(0, peak - 1).toFixed(4)),
    points,
    css: `linear(${points.join(', ')})`,
  };
}

function build() {
  const springs = {};
  for (const [name, duration] of Object.entries(SPRINGS)) {
    springs[name] = { duration, flat: spring(duration, 0), bouncy: spring(duration, BOUNCE) };
  }

  const css = [
    '/* GENERATED by scripts/motion-tokens.cjs - edit that file, then run it. */',
    '',
    ':root {',
    `  /* Springs: perceptual duration, bounce 0 or ${BOUNCE}; --settle-* is the CSS duration to pair with each. */`,
  ];
  for (const [name, { duration, flat, bouncy }] of Object.entries(springs)) {
    css.push(`  /* ${name}: ${Math.round(duration * 1000)} ms. Bounce ${BOUNCE} overshoots ${(bouncy.overshoot * 100).toFixed(1)}%. */`);
    css.push(`  --spring-${name}: ${flat.css};`);
    css.push(`  --settle-${name}: ${flat.settleMs}ms;`);
    css.push(`  --spring-${name}-bounce: ${bouncy.css};`);
    css.push(`  --settle-${name}-bounce: ${bouncy.settleMs}ms;`);
  }
  for (const [name, value] of Object.entries(FIXED)) css.push(`  --${name}: ${value};`);
  css.push('}', '');

  const ms = (value) => Number.parseInt(value, 10);
  const ts = [
    '// GENERATED by scripts/motion-tokens.cjs - edit that file, then run it.',
    '/* eslint-disable */',
    '',
    'export interface SpringToken {',
    '  /** Perceptual duration, in milliseconds. */',
    '  durationMs: number;',
    '  /** How long it takes to come to rest: the duration to animate with. */',
    '  settleMs: number;',
    '  /** The curve, as CSS: a transition or WAAPI easing. */',
    '  easing: string;',
    '  /** The same curve sampled evenly from 0 to settleMs, for a canvas. */',
    '  points: readonly number[];',
    '}',
    '',
    `export const BOUNCE = ${BOUNCE};`,
    '',
    'export const SPRINGS = {',
  ];
  for (const [name, { duration, flat, bouncy }] of Object.entries(springs)) {
    for (const [suffix, curve] of [['', flat], ['Bounce', bouncy]]) {
      ts.push(
        `  ${name}${suffix}: { durationMs: ${Math.round(duration * 1000)}, settleMs: ${curve.settleMs}, easing: '${curve.css}', points: [${curve.points.join(', ')}] },`,
      );
    }
  }
  ts.push('} as const satisfies Record<string, SpringToken>;', '');
  ts.push(`export const EXIT_MS = ${ms(FIXED['dur-exit'])};`);
  ts.push(`export const EXIT_FAST_MS = ${ms(FIXED['dur-exit-fast'])};`);
  ts.push(`export const REDUCED_MS = ${ms(FIXED['dur-reduced'])};`);
  ts.push(`export const EASE_EXIT = '${FIXED['ease-exit']}';`);
  ts.push(`export const EASE_OUT = '${FIXED['ease-out']}';`);
  ts.push('');

  return { css: css.join('\n'), ts: ts.join('\n'), springs, BOUNCE };
}

module.exports = { build, spring, springAt, BOUNCE, SPRINGS, FIXED };

if (require.main === module) {
  const root = join(__dirname, '..');
  const { css, ts, springs } = build();
  writeFileSync(join(root, 'src/renderer/motion/tokens.css'), css);
  writeFileSync(join(root, 'src/renderer/motion/tokens.generated.ts'), ts);
  for (const [name, { flat, bouncy }] of Object.entries(springs)) {
    console.log(`${name.padEnd(9)} settles ${flat.settleMs} ms flat, ${bouncy.settleMs} ms with bounce ${BOUNCE} (overshoot ${(bouncy.overshoot * 100).toFixed(1)}%)`);
  }
}
